name: sextointento

on:
    push:
        branches:
            - main

job:
    jobcuatro:
        runs-on: ubuntu-18.04
        steps:
            - name: stetpsexto
            run: echo "Hola sexto intento"

